/**
 * Brief: dump everything slipstream knows about a project into one Markdown
 * document, so someone, or a fresh Claude session, starting later gets the whole
 * picture: what the project is, how it is organised, what has been built, the
 * durable memory, the lessons, the instincts and the recent work. projectBrief
 * is pure over the gathered pieces; assembleBrief loads them from the store.
 */

import type { OverviewMap } from "./overview.js";
import type { Conversation } from "../memory/conversation.js";
import { summariseMap, narrateOverview } from "./overview.js";
import { projectInsights } from "./insights.js";
import { deriveInstincts } from "../memory/instincts.js";
import {
  loadObservations,
  listMemories,
  listConversations,
  distillProjectLessons
} from "../memory/index.js";
import { listSessions } from "./log.js";
import { generateMap } from "../map/index.js";
import { loadSavings, summarizeSavings } from "../context/savings.js";
import { estimateCost } from "../context/cost.js";

export interface BriefInput {
  name: string;
  version: string;
  narration: string;
  map: OverviewMap | null;
  built: string;
  memories: { name: string; type: string; description: string }[];
  lessons: { title: string; summary: string; count: number }[];
  instincts: { subject: string; note: string; confidence: number }[];
  recent: { ask: string; summary: string }[];
  savedTokens: number;
  savedUsd: number;
  generatedAt: string;
}

export function projectBrief(input: BriefInput): string {
  const out: string[] = [];
  out.push(`# ${input.name} ${input.version ? `v${input.version}` : ""}`.trim());
  out.push("");
  out.push(`> Project knowledge brief, generated by slipstream on ${input.generatedAt}. Everything below is recovered from the local observation store and the code map; read it to pick up the project cold.`);
  out.push("");

  out.push("## What this is");
  out.push("");
  out.push(input.narration || "(no narration available)");
  out.push("");

  if (input.map && input.map.areas.length) {
    out.push("## How it is organised");
    out.push("");
    out.push("| Area | Files | Symbols | Role |");
    out.push("|---|---:|---:|---|");
    for (const a of input.map.areas) {
      out.push(`| ${a.area} | ${a.files} | ${a.symbols} | ${a.role} |`);
    }
    out.push("");
  }

  out.push("## What has been built");
  out.push("");
  out.push(input.built || "(nothing observed yet)");
  if (input.savedTokens > 0) {
    out.push("");
    out.push(`Scoped reads have saved approximately ${input.savedTokens.toLocaleString("en-GB")} tokens, about $${input.savedUsd.toFixed(2)}.`);
  }
  out.push("");

  out.push("## Recent work");
  out.push("");
  if (input.recent.length) for (const r of input.recent) out.push(`- ${r.summary || r.ask}`);
  else out.push("(no recorded conversation yet)");
  out.push("");

  out.push("## Durable memory");
  out.push("");
  if (input.memories.length) for (const m of input.memories) out.push(`- **${m.name}** (${m.type}): ${m.description}`);
  else out.push("(no durable memories yet)");
  out.push("");

  out.push("## Lessons learned");
  out.push("");
  if (input.lessons.length) for (const l of input.lessons) out.push(`- **${l.title}**: ${l.summary}${l.count ? ` (${l.count} observations)` : ""}`);
  else out.push("(no lessons distilled yet)");
  out.push("");

  out.push("## Instincts, patterns that recur");
  out.push("");
  if (input.instincts.length) for (const i of input.instincts) out.push(`- ${i.note} (${Math.round(i.confidence * 100)}% confidence)`);
  else out.push("(no recurring patterns yet)");
  out.push("");

  return out.join("\n").trim() + "\n";
}

/** Gather every piece from the store and render the brief. Does disk IO. */
export async function assembleBrief(root: string, name: string, version: string, generatedAt: string): Promise<string> {
  const [mapRes, obs, sessions, memories, lessons, conversations, savings] = await Promise.all([
    generateMap(root).catch(() => null),
    loadObservations(root).catch(() => []),
    listSessions(root).catch(() => [] as string[]),
    listMemories(root).catch(() => []),
    distillProjectLessons(root, { minCount: 2, limit: 8 }).catch(() => [] as { title?: string; topic?: string; summary?: string; body?: string; count?: number }[]),
    listConversations(root).catch(() => [] as Awaited<ReturnType<typeof listConversations>>),
    loadSavings(root).then(summarizeSavings).catch(() => ({ scopedReads: 0, savedTokens: 0, pct: 0 }))
  ]);
  const map = mapRes ? summariseMap(mapRes) : null;
  const counts = { sessions: sessions.length, observations: obs.length, memories: memories.length };
  const built = projectInsights({
    observations: obs,
    sessionCount: sessions.length,
    memoryCount: memories.length,
    optPct: savings.pct,
    savedTokens: savings.savedTokens,
    scopedReads: savings.scopedReads
  }).paragraph;
  const recentExchanges = (conversations as Conversation[])
    .flatMap((c) => c.exchanges.map((e) => ({ ask: e.ask, summary: e.summary, ts: e.ts })))
    .sort((a, b) => (a.ts < b.ts ? 1 : -1))
    .slice(0, 8);

  return projectBrief({
    name,
    version,
    narration: map ? narrateOverview(map, counts) : "",
    map,
    built,
    memories: memories.map((m: { name: string; type: string; description: string }) => ({ name: m.name, type: m.type, description: m.description })),
    lessons: lessons.map((l: { title?: string; topic?: string; summary?: string; body?: string; count?: number }) => ({ title: l.title ?? l.topic ?? "lesson", summary: l.summary ?? l.body ?? "", count: l.count ?? 0 })),
    instincts: deriveInstincts(obs).slice(0, 10).map((i) => ({ subject: i.subject, note: i.note, confidence: i.confidence })),
    recent: recentExchanges.map((e) => ({ ask: e.ask, summary: e.summary })),
    savedTokens: savings.savedTokens,
    savedUsd: estimateCost(savings.savedTokens).usd,
    generatedAt
  });
}
